### ISSUE TITLE
Deployment Server & Domain

### ISSUE THREAD

**Issue by nut1414** [cpe-kmutt-student/road-to-engineer-2023#12]
on what are we deploying on and how to integrate with the backend?

**Comment by riflowth** [comment]
@nut1414
If you gonna request a VM from the Computer center at our university, it takes too much time from my experience. I suggest you buy a VM by yourself and claim expenses later.

**Comment by nut1414** [comment]
Is it possible to use github page to host our frontpage bc we are not responsible for the backend? p'@riflowth

**Comment by riflowth** [comment]
@nut1414 I'm sorry for not getting back to you sooner.
I see you are using Vercel now. It's okay. Not many people access our website, I guess.

**Comment by nut1414** [comment]
thanks krub 😀
